version : '3.1'
services:
  backend:
    build: .
    ports:
      - 9000:9000
    links:
      - "db"
  db:
    image: postgres:12-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres